const features=[
[2,'AI Crop Planning','Supervised / recommendation','Core Lifecycle'],[3,'Smart Irrigation','Regression / forecasting','Core Lifecycle'],[4,'Crop Health AI','Computer vision','Core Lifecycle'],[9,'Harvest & Market','Forecasting / ranking','Core Lifecycle'],
[11,'Satellite Crop Stress Prediction','Remote sensing','Computer Vision'],[12,'Drone/Video Plant Counting','Object detection','Computer Vision'],[13,'Weed Species Classification','Classification / detection','Computer Vision'],[14,'Grain Quality Scoring','Vision / quality classification','Computer Vision'],
[15,'Hyperlocal Mandi Price Forecasting','Time-series','Forecasting'],[16,'Yield Forecasting with Uncertainty','Probabilistic time-series','Forecasting'],[17,'Water Demand Forecasting','Time-series / regression','Forecasting'],[18,'Soil Health Modeling','Gaussian Process / regression','Agronomy ML'],[19,'Variety Recommendation Engine','Recommendation / ranking','Agronomy ML'],[20,'Pest Outbreak Spread Prediction','Spatiotemporal / simulation','Agronomy ML'],
[21,'Voice-First AI Assistant','Speech / NLP','NLP / Multimodal'],[22,'Multimodal Query Understanding','Vision-language','NLP / Multimodal'],[23,'RL Crop Rotation Planner','Reinforcement learning','RL / Optimization'],[24,'Dynamic Equipment/Logistics Routing','OR-Tools VRP','RL / Optimization'],[25,'Federated Learning Across Farms','Federated ML','Federated / Data Network'],[26,'Learned Buyer-Farmer Matching','Recommendation / ranking','Federated / Data Network'],[27,'Counterfactual What-If Simulator','Causal / counterfactual ML','Moonshot'],[28,'Anomaly Detection for Fraud/Quality','Anomaly detection','Moonshot'],[29,'Climate Risk Scoring per Field','Climate / geospatial ML','Moonshot'],[40,'Variable-Rate Application Engine','Spatial ML','Precision Farming'],[44,'AI-Recommended Inputs & Delivery','Ranking / recommendation','Marketplace'],[48,'CEA Energy Optimization','Optimization / ML hybrid','CEA'],[50,'Farm Credit & Alternative-Data Loan Marketplace','Credit ML','Finance'],[51,'Livestock & Dairy Health Management','Vision / classification','Livestock'],[55,'Institutional & Retail B2B Sales Channel','Recommendation / ranking','Marketplace'],[56,'Community Pest & Disease Surveillance Network','Aggregation / ML','Community']
];
const groups=['All',...new Set(features.map(f=>f[3]))];let active='All';const filters=document.querySelector('#filters');const grid=document.querySelector('#grid');const search=document.querySelector('#search');
filters.innerHTML=groups.map(g=>`<button class="filter ${g==='All'?'active':''}" data-group="${g}">${g}</button>`).join('');filters.addEventListener('click',e=>{if(!e.target.matches('button'))return;active=e.target.dataset.group;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===e.target));render()});search.addEventListener('input',render);
function render(){const q=search.value.toLowerCase();const list=features.filter(f=>(active==='All'||f[3]===active)&&f.slice(1).join(' ').toLowerCase().includes(q));grid.innerHTML=list.map(f=>`<article class="card"><span class="num">FEATURE #${String(f[0]).padStart(2,'0')}</span><h3>${f[1]}</h3><p>${f[2]}<br>Separate dataset links and source notes available in the master catalog.</p><div class="card-bottom"><span class="tag">${f[3]}</span><a class="open" href="MASTER_DATASETS.md#feature-${f[0]}">View data ↗</a></div></article>`).join('')||'<p>No matching features found.</p>'}render();
